# Uncomment the next line to define a global platform for your project
platform :macos, '12.3'

target 'lol' do
  # Comment the next line if you don't want to use dynamic frameworks
  # use_frameworks!

  # Pods for lol
  pod 'SwiftSoup'
end
